version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            schema: haystack-v2
            uri: >-
              mongodb+srv://mike:nkH3fl5sCJJDvj08@haystackcluster0-vqy8h.mongodb.net/test?retryWrites=true&w=majority